__version__: str


class Orientation:
    CLOCKWISE: 'Orientation' = ...
    COLLINEAR: 'Orientation' = ...
    COUNTERCLOCKWISE: 'Orientation' = ...

    @property
    def value(self) -> int:
        ...

    def __new__(cls, value: int) -> 'Orientation':
        ...

    def __repr__(self) -> str:
        ...
