mod bentley_ottmann;
pub mod bounded;
mod clipping;
mod constants;
mod contracts;
pub mod geometries;
mod iteration;
pub mod locatable;
mod operations;
pub mod oriented;
mod python_binding;
pub mod relatable;
mod relating;
mod seidel;
mod slice_sequence;
mod sweeping;
pub mod traits;
mod triangulation;
